### ISSUE TITLE
Custom service location issue

### ISSUE THREAD

**Issue by doston0000** [regulaforensics/FaceSDK-iOS#1] opened 2021-03-20 13:26 UTC
I have following problem when using your sdk, if i set custom service location like here https://docs.regulaforensics.com/ios-face/service-location using my own url, somehow it subscripts my url, for example
my url: www.somedomain.com/regula/ 
 Makematchrequest adds /api/faces/ into my url and makes it www.somedomain.com/api/faces/ but regula path subscripted can u help with that

**Comment by ikliashchou** [comment] 2021-03-20 22:38
Hello,
As you can see in docs, you have to set url to the host only (including port). We expect our service to be present there and have specific endpoints, where /api/faces/ is the API methods prefix. This is by design.

**Comment by ucookteam** [comment] 2021-03-21 05:32
@ikliashchou Thank you for response, but we are using your sdk on Bank, and we can not  use it on direct host because of bank security regulation
p.s on android same sdk with same url works without problem url: www.somedomain.com/regula/ + your method prefix 
www.somedomain.com/regula/api/faces 
on ios same url beomes www.somedomain.com/api/faces :) please help with that)

**Comment by doston0000** [comment] 2021-03-21 05:45
@ikliashchou Thank you for response, but we are using your sdk on Bank, and we can not use it on direct host because of bank security regulation
p.s on android same sdk with same url works without problem url: www.somedomain.com/regula/ + your method prefix
www.somedomain.com/regula/api/faces
on ios same url becomes www.somedomain.com/api/faces :) please help with that)

**Comment by DzmitrySmaliakou** [comment] 2021-03-21 11:47
@doston0000 Hello,
Thank you for your report. This issue should be fixed in the latest beta version. Please check it out:
pod 'FaceSDKBeta', '5.4.249'

**Comment by doston0000** [comment] 2021-03-21 12:09
@DmitrySmolyakov i guess its not available yet
[!] CocoaPods could not find compatible versions for pod "FaceSDKBeta"

**Comment by DzmitrySmaliakou** [comment] 2021-03-21 12:11
It could be not cached yet. Direct link to this version: https://pods.regulaforensics.com/FaceSDKBeta/5.4.249/

**Comment by doston0000** [comment] 2021-03-21 12:12
thank you 🙏  i will let you know after testing it)

**Comment by doston0000** [comment] 2021-03-21 12:22
i could not compile it) can you recheck it @DmitrySmolyakov 
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_RGLComparedFacesPair", referenced from:
      objc-class-ref in FaceRecognition.o
  "_OBJC_CLASS_$_RGLMatchFacesRequest", referenced from:
      objc-class-ref in FaceRecognition.o
  "_OBJC_CLASS_$_RGLImage", referenced from:
      objc-class-ref in FaceRecognition.o
  "_OBJC_CLASS_$_RGLFace", referenced from:
      objc-class-ref in FaceRecognition.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by DzmitrySmaliakou** [comment] 2021-03-21 13:02
@doston0000 Sorry, some problems with our builder, this version should be fine: https://pods.regulaforensics.com/FaceSDKBeta/5.4.254/

**Comment by doston0000** [comment] 2021-03-21 13:03
yeah i saw it im checking it right now

**Comment by doston0000** [comment] 2021-03-21 13:12
@DmitrySmolyakov thanks its working

**Comment by DzmitrySmaliakou** [comment] 2021-03-21 13:13
Happy to help

**Closed as completed by DzmitrySmaliakou** 2021-03-21 13:13 UTC
